import { Hono } from 'hono';
import { LineClient } from '@line-crm/line-sdk';
import { getFriendById } from '@line-crm/db';
import type { Env } from '../index.js';

const richMenus = new Hono<Env>();

// GET /api/rich-menus — list all rich menus from LINE API
richMenus.get('/api/rich-menus', async (c) => {
  try {
    const lineClient = new LineClient(c.env.LINE_CHANNEL_ACCESS_TOKEN);
    const result = await lineClient.getRichMenuList();
    return c.json({ success: true, data: result.richmenus ?? [] });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('GET /api/rich-menus error:', message);
    return c.json({ success: false, error: `Failed to fetch rich menus: ${message}` }, 500);
  }
});

// POST /api/rich-menus — create a rich menu via LINE API
richMenus.post('/api/rich-menus', async (c) => {
  try {
    const body = await c.req.json();
    const lineClient = new LineClient(c.env.LINE_CHANNEL_ACCESS_TOKEN);
    const result = await lineClient.createRichMenu(body);
    return c.json({ success: true, data: result }, 201);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('POST /api/rich-menus error:', message);
    return c.json({ success: false, error: `Failed to create rich menu: ${message}` }, 500);
  }
});

// DELETE /api/rich-menus/:id — delete a rich menu
richMenus.delete('/api/rich-menus/:id', async (c) => {
  try {
    const richMenuId = c.req.param('id');
    const lineClient = new LineClient(c.env.LINE_CHANNEL_ACCESS_TOKEN);
    await lineClient.deleteRichMenu(richMenuId);
    return c.json({ success: true, data: null });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('DELETE /api/rich-menus/:id error:', message);
    return c.json({ success: false, error: `Failed to delete rich menu: ${message}` }, 500);
  }
});

// POST /api/rich-menus/:id/default — set rich menu as default for all users
richMenus.post('/api/rich-menus/:id/default', async (c) => {
  try {
    const richMenuId = c.req.param('id');
    const lineClient = new LineClient(c.env.LINE_CHANNEL_ACCESS_TOKEN);
    await lineClient.setDefaultRichMenu(richMenuId);
    return c.json({ success: true, data: null });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('POST /api/rich-menus/:id/default error:', message);
    return c.json({ success: false, error: `Failed to set default rich menu: ${message}` }, 500);
  }
});

// POST /api/friends/:friendId/rich-menu — link rich menu to a specific friend
richMenus.post('/api/friends/:friendId/rich-menu', async (c) => {
  try {
    const friendId = c.req.param('friendId');
    const body = await c.req.json<{ richMenuId: string }>();

    if (!body.richMenuId) {
      return c.json({ success: false, error: 'richMenuId is required' }, 400);
    }

    const db = c.env.DB;
    const friend = await getFriendById(db, friendId);
    if (!friend) {
      return c.json({ success: false, error: 'Friend not found' }, 404);
    }

    const lineClient = new LineClient(c.env.LINE_CHANNEL_ACCESS_TOKEN);
    await lineClient.linkRichMenuToUser(friend.line_user_id, body.richMenuId);

    return c.json({ success: true, data: null });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('POST /api/friends/:friendId/rich-menu error:', message);
    return c.json({ success: false, error: `Failed to link rich menu to friend: ${message}` }, 500);
  }
});

// DELETE /api/friends/:friendId/rich-menu — unlink rich menu from a specific friend
richMenus.delete('/api/friends/:friendId/rich-menu', async (c) => {
  try {
    const friendId = c.req.param('friendId');
    const db = c.env.DB;

    const friend = await getFriendById(db, friendId);
    if (!friend) {
      return c.json({ success: false, error: 'Friend not found' }, 404);
    }

    const lineClient = new LineClient(c.env.LINE_CHANNEL_ACCESS_TOKEN);
    await lineClient.unlinkRichMenuFromUser(friend.line_user_id);

    return c.json({ success: true, data: null });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('DELETE /api/friends/:friendId/rich-menu error:', message);
    return c.json({ success: false, error: `Failed to unlink rich menu from friend: ${message}` }, 500);
  }
});

// POST /api/rich-menus/setup-naturism — naturism用リッチメニュー一括セットアップ v3
// 8ボタン（本番同等レイアウト）: 左2列大 + 右1列上下分割×4
// フロー: 1. 既存デフォルト削除 → 2. 構造作成 → 3. 画像アップロード → 4. デフォルト設定
richMenus.post('/api/rich-menus/setup-naturism', async (c) => {
  try {
    const lineClient = new LineClient(c.env.LINE_CHANNEL_ACCESS_TOKEN);
    const liffUrl = c.env.LIFF_URL || 'https://liff.line.me/2009713578-NbdHyFZf';

    // Step 0: 既存デフォルトリッチメニューを解除（新規設定のため）
    try {
      await lineClient.deleteDefaultRichMenu();
    } catch {
      // デフォルトが無い場合は無視
    }

    // naturism リッチメニュー定義（2500×1686 フルサイズ）
    // レイアウト: 左2列(各833px) + 右1列(834px, 上下分割)
    const colW = 833;       // 左2列の幅
    const colWR = 834;      // 右列の幅 (2500 - 833*2 = 834)
    const rowH = 843;       // 行の高さ (1686/2)
    const halfH = 421;      // 右列セル高さ (上)
    const halfH2 = 422;     // 右列セル高さ (下, 843-421=422)

    const richMenuBody = {
      size: { width: 2500, height: 1686 },
      selected: true,
      name: 'naturism メインメニュー v3',
      chatBarText: 'メニュー',
      areas: [
        // 上段左: ホームページ
        {
          bounds: { x: 0, y: 0, width: colW, height: rowH },
          action: { type: 'uri' as const, label: 'ホームページ', uri: 'https://naturism-diet.com' },
        },
        // 上段中: カテゴリー
        {
          bounds: { x: colW, y: 0, width: colW, height: rowH },
          action: { type: 'uri' as const, label: 'カテゴリー', uri: 'https://naturism-diet.com/collections' },
        },
        // 上段右上: 友達紹介
        {
          bounds: { x: colW * 2, y: 0, width: colWR, height: halfH },
          action: { type: 'uri' as const, label: '友達紹介', uri: `${liffUrl}#referral` },
        },
        // 上段右下: マイランク
        {
          bounds: { x: colW * 2, y: halfH, width: colWR, height: halfH2 },
          action: { type: 'uri' as const, label: 'マイランク', uri: `${liffUrl}#rank` },
        },
        // 下段左: 配送状況をみる
        {
          bounds: { x: 0, y: rowH, width: colW, height: rowH },
          action: { type: 'uri' as const, label: '配送状況をみる', uri: `${liffUrl}#delivery` },
        },
        // 下段中: 購入履歴・再購入
        {
          bounds: { x: colW, y: rowH, width: colW, height: rowH },
          action: { type: 'uri' as const, label: '購入履歴・再購入', uri: `${liffUrl}#reorder` },
        },
        // 下段右上: SNS
        {
          bounds: { x: colW * 2, y: rowH, width: colWR, height: halfH },
          action: { type: 'uri' as const, label: 'SNS', uri: 'https://www.instagram.com/naturism_supplement/' },
        },
        // 下段右下: Q&A お問い合わせ
        {
          bounds: { x: colW * 2, y: rowH + halfH, width: colWR, height: halfH2 },
          action: { type: 'message' as const, label: 'Q&A お問い合わせ', text: 'お問い合わせ' },
        },
      ],
    };

    // Step 1: リッチメニュー作成
    const createResult = await lineClient.createRichMenu(richMenuBody);
    const richMenuId = createResult.richMenuId;

    // Step 2: 画像アップロード（事前生成済み 2500×1686 PNG）
    const pngData = base64ToArrayBuffer(NATURISM_MENU_PNG_B64);
    await lineClient.uploadRichMenuImage(richMenuId, pngData, 'image/png');

    // Step 3: デフォルトに設定
    await lineClient.setDefaultRichMenu(richMenuId);

    return c.json({
      success: true,
      data: {
        richMenuId,
        areas: richMenuBody.areas.map((a) => ({ label: a.action.label, type: a.action.type })),
        message: 'リッチメニュー v3（8ボタン）を作成・画像アップロード・デフォルト設定まで完了。',
      },
    }, 201);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('POST /api/rich-menus/setup-naturism error:', message);
    return c.json({ success: false, error: `Failed to setup naturism rich menu: ${message}` }, 500);
  }
});

/**
 * naturism リッチメニュー用PNG（2500x1686 ソリッド #06C755）
 * Node.jsで事前生成済み（zlib level-9 圧縮）— 14,923バイト
 * Worker内でのリアルタイム生成はCPU制限超過のため使用しない
 */
const NATURISM_MENU_PNG_B64 =
  'iVBORw0KGgoAAAANSUhEUgAACcQAAAaWCAIAAAAWH7t/AAA6EklEQVR42uzZMQ0AAAzDsF5jOMyltX8YLBlB3mS6AAAAAAAAADyRAAAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwExVAQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwExVAQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADNVAgAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADNVBQAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADNVBQAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUCQAAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFADj27JgEAAAAYFD/1hYRTLB3VVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmbpCVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmbpCVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ+oEVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ+oKVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ+oKVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnakTVFVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVVdaZWVVVVVVVVdaZWVVVVVVVVnalVVVVVVVVVZ2pVVVVVVVXVmVpVVVVVVVV1plZVVVVVVVWdqVVVVVVVVVVnalVVVVVVVdWZWlVVVVVVVXWmVlVVVVVVVZ2pVVVVVVVVVWdqVVVVVVVV1ZlaVVVVVVVpz45pAAAAAAT1b20BI7CRwFcAzFQAAAAAAAAAM1UFAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAM1UFAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQJAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQVAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQVAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMlAAAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFNVAAAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAADMVAAAAAAAAwEwFAAAAAAAAMFMBAAAAAAAAzFQAAAAAAAAAMxUAAAAAAADATAUAAAAAAAAwUwEAAAAAAADMVAAAAAAAAAAzFQAAAAAAAMBMBQAAAAAAADBTAQAAAAAAAMxUAAAAAAAAAMxUAAAAAAAAgBdhzNnC4l8DggAAAABJRU5ErkJggg==';

/** base64文字列をArrayBufferに変換 */
function base64ToArrayBuffer(b64: string): ArrayBuffer {
  const binaryString = atob(b64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes.buffer;
}

// GET /api/rich-menus/image-guide — リッチメニュー画像テンプレートHTML v3
// 8ボタン・シルバーアクセント付き豪華デザイン
// ブラウザで開いてスクリーンショット（2500x1686）を撮って画像として使用
richMenus.get('/api/rich-menus/image-guide', async (c) => {
  return c.html(`<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700;900&display=swap');
* { margin: 0; padding: 0; box-sizing: border-box; }
body { width: 2500px; height: 1686px; font-family: 'Noto Sans JP', 'Hiragino Sans', sans-serif; overflow: hidden; }

.container {
  width: 2500px; height: 1686px;
  display: grid;
  grid-template-columns: 833px 833px 834px;
  grid-template-rows: 843px 843px;
  background: linear-gradient(160deg, #f8f9fa 0%, #e8eaed 50%, #d4d7dc 100%);
}

/* 大セル（左2列） */
.cell-large {
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  gap: 24px; position: relative; overflow: hidden;
  border: 1px solid rgba(192,192,192,0.3);
}
.cell-large .icon { font-size: 120px; filter: drop-shadow(0 4px 12px rgba(0,0,0,0.15)); }
.cell-large .label {
  font-size: 48px; font-weight: 900; letter-spacing: 3px;
  background: linear-gradient(135deg, #3a3a3a 0%, #666 50%, #3a3a3a 100%);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent;
  text-shadow: none;
}
.cell-large .sub {
  font-size: 24px; color: #888; font-weight: 400; letter-spacing: 1px;
}
/* シルバーシャイン効果 */
.cell-large::after {
  content: ''; position: absolute; top: -50%; left: -50%;
  width: 200%; height: 200%;
  background: linear-gradient(45deg, transparent 40%, rgba(255,255,255,0.08) 50%, transparent 60%);
  pointer-events: none;
}

/* 右列の小セル（上下分割） */
.right-col {
  display: grid; grid-template-rows: 421px 422px;
  border: 1px solid rgba(192,192,192,0.3);
}
.cell-small {
  display: flex; flex-direction: row; align-items: center; justify-content: center;
  gap: 16px; position: relative; overflow: hidden;
  border-bottom: 1px solid rgba(192,192,192,0.2);
}
.cell-small .icon { font-size: 72px; filter: drop-shadow(0 2px 6px rgba(0,0,0,0.12)); }
.cell-small .label {
  font-size: 36px; font-weight: 700;
  background: linear-gradient(135deg, #3a3a3a 0%, #555 100%);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent;
}

/* 各セルの背景 — 淡いグラデーション + シルバーボーダー */
.bg-home {
  background: linear-gradient(135deg, #f0f4f8 0%, #e2e8f0 100%);
  border-left: 4px solid rgba(180,180,200,0.4);
}
.bg-category {
  background: linear-gradient(135deg, #f0f4f8 0%, #e2e8f0 100%);
}
.bg-referral {
  background: linear-gradient(135deg, #eef6f0 0%, #d4edda 100%);
}
.bg-rank {
  background: linear-gradient(135deg, #fff9e6 0%, #ffeeba 100%);
}
.bg-delivery {
  background: linear-gradient(135deg, #e8f4fd 0%, #cce5ff 100%);
  border-left: 4px solid rgba(180,180,200,0.4);
}
.bg-reorder {
  background: linear-gradient(135deg, #e8f4fd 0%, #cce5ff 100%);
}
.bg-sns {
  background: linear-gradient(135deg, #f3eefb 0%, #e2d5f1 100%);
}
.bg-qa {
  background: linear-gradient(135deg, #f0f0f0 0%, #ddd 100%);
}

/* シルバーのコーナー装飾 */
.cell-large::before, .cell-small::before {
  content: ''; position: absolute; top: 8px; left: 8px; right: 8px; bottom: 8px;
  border: 1px solid rgba(192,192,192,0.15); border-radius: 16px;
  pointer-events: none;
}
</style></head>
<body>
<div class="container">
  <!-- 上段左: ホームページ -->
  <div class="cell-large bg-home">
    <span class="icon">🖥️</span>
    <span class="label">ホームページ</span>
    <span class="sub">naturism公式サイト</span>
  </div>
  <!-- 上段中: カテゴリー -->
  <div class="cell-large bg-category">
    <span class="icon">🔍</span>
    <span class="label">カテゴリー</span>
    <span class="sub">商品を探す</span>
  </div>
  <!-- 上段右（分割） -->
  <div class="right-col">
    <div class="cell-small bg-referral">
      <span class="icon">👥</span>
      <span class="label">友達紹介</span>
    </div>
    <div class="cell-small bg-rank">
      <span class="icon">🏅</span>
      <span class="label">マイランク</span>
    </div>
  </div>
  <!-- 下段左: 配送状況 -->
  <div class="cell-large bg-delivery">
    <span class="icon">🚚</span>
    <span class="label">配送状況をみる</span>
    <span class="sub">お届け状況を確認</span>
  </div>
  <!-- 下段中: 購入履歴・再購入 -->
  <div class="cell-large bg-reorder">
    <span class="icon">🛒</span>
    <span class="label">購入履歴・再購入</span>
    <span class="sub">ワンタップで再注文</span>
  </div>
  <!-- 下段右（分割） -->
  <div class="right-col">
    <div class="cell-small bg-sns">
      <span class="icon">💬</span>
      <span class="label">SNS</span>
    </div>
    <div class="cell-small bg-qa">
      <span class="icon">✉️</span>
      <span class="label">Q&A</span>
    </div>
  </div>
</div>
</body></html>`);
});

export { richMenus };

// POST /api/rich-menus/:id/image — upload rich menu image (accepts base64 body or binary)
richMenus.post('/api/rich-menus/:id/image', async (c) => {
  try {
    const richMenuId = c.req.param('id');
    const contentType = c.req.header('content-type') ?? '';

    let imageData: ArrayBuffer;
    let imageContentType: 'image/png' | 'image/jpeg' = 'image/png';

    if (contentType.includes('application/json')) {
      // Accept base64 encoded image in JSON body
      const body = await c.req.json<{ image: string; contentType?: string }>();
      if (!body.image) {
        return c.json({ success: false, error: 'image (base64) is required' }, 400);
      }
      // Strip data URI prefix if present
      const base64 = body.image.replace(/^data:image\/\w+;base64,/, '');
      const binaryString = atob(base64);
      const bytes = new Uint8Array(binaryString.length);
      for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
      imageData = bytes.buffer;
      if (body.contentType === 'image/jpeg') imageContentType = 'image/jpeg';
    } else if (contentType.includes('image/')) {
      // Accept raw binary upload
      imageData = await c.req.arrayBuffer();
      imageContentType = contentType.includes('jpeg') || contentType.includes('jpg') ? 'image/jpeg' : 'image/png';
    } else {
      return c.json({ success: false, error: 'Content-Type must be application/json (with base64) or image/png or image/jpeg' }, 400);
    }

    const lineClient = new LineClient(c.env.LINE_CHANNEL_ACCESS_TOKEN);
    await lineClient.uploadRichMenuImage(richMenuId, imageData, imageContentType);

    return c.json({ success: true, data: null });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('POST /api/rich-menus/:id/image error:', message);
    return c.json({ success: false, error: `Failed to upload rich menu image: ${message}` }, 500);
  }
});
