/**
 * ポータル shop タブ「定期便のお手続き」カード (Ultraplan PR-5)。
 *
 * gate `LIFF_SUB_CARD_ENABLED` (既定 off = dark)。off の間、liff-pages.ts は本 fragment を
 * 一切 emit しない (HTML/CSS/JS とも 0 byte)。on のとき PR-4 の 3 endpoint を呼ぶ:
 *   GET  /api/liff/sub-contracts               — 契約一覧 + open intent
 *   POST /api/liff/sub-contracts/:id/intents   — 受理 (skip|date|pause|cancel)
 *   POST /api/liff/sub-intents/:id/undo        — 取り消し
 *
 * UX 規律 (docs/SUBSCRIPTION_UX_TAP_MINIMAL_2026-07-25.md):
 *   - §1: カードに出したタップは常に受理される (出せない op はボタン自体を出さない)。
 *     受理は「承りました」止まり — 完了を宣言しない
 *   - §2: スキップ/一時停止 = 1 タップ、日付変更 = 2 タップ (選ぶ→確定)、解約 = 2 タップ (確認あり)
 *   - §4-1: promised_by の開示。late_promise (409) は開示 → 顧客が選んで ack 再送
 *   - §1-3: 受理済み intent には [取り消す] を必ず併記。取り消し可否は state (サーバ) が決める
 *   - §7: 60代トークン — 本文 16px / 行間 1.6 / タップ 48px / 日付は 20px bold #0f766e /
 *     1 カードのボタン最大 3 (解約はテキストリンクに降格して 3 本制限を守る)
 *
 * コーディング規律 (CLAUDE.md — LIFF inline JS):
 *   - client JS 文字列に「バックスラッシュ+シングルクォート」を書かない
 *   - script 終了タグを literal で書かない (seam 側の inlineScriptBody が最終防衛)
 *   - onclick は引数なしの名前付き関数 + data-* 属性のみ (引用符ネスト禁止)
 *   - 動的値の DOM 挿入は必ず esc() (liff-pages.ts 本体の関数を再利用)
 */

/** カードの静的 HTML。shop セクション先頭に置く。データ確定まで非表示 (skeleton も出さない —
 *  契約が無い大多数の顧客に空カードの chrome を見せない)。 */
export function subCardHtml(): string {
  return [
    '<!-- 定期便のお手続き (Ultraplan PR-5, gate LIFF_SUB_CARD_ENABLED) -->',
    '<div id="sub-contracts-card" class="card p-4" style="display:none">',
    '  <div class="flex items-center gap-2 mb-2">',
    '    <span style="font-size:20px">📦</span>',
    '    <p class="sc-title">定期便のお手続き</p>',
    '  </div>',
    '  <div id="sub-contracts-list"></div>',
    '</div>',
  ].join('\n      ');
}

/** カード専用 CSS。既存トークン (--action / --ink-2 / --hairline 等) を使い新色を増やさない。 */
export function subCardCss(): string {
  return [
    '/* ─ 定期便カード (PR-5) — §7 60代トークン: 16px/1.6/48px/日付20px ─ */',
    '.sc-title{font-size:16px;font-weight:700;color:#052422}',
    '.sc-item{border:1px solid var(--hairline);border-radius:14px;padding:14px;margin-top:10px}',
    '.sc-plan{font-size:16px;font-weight:700;color:#052422;line-height:1.6}',
    '.sc-date{font-size:20px;font-weight:700;color:#0f766e;line-height:1.6}',
    '.sc-body{font-size:16px;color:#3f4b55;line-height:1.6}',
    '.sc-deadline{font-size:16px;color:#66727d;line-height:1.6}',
    '.sc-btn{min-height:48px;font-size:16px;font-weight:700;width:100%;border-radius:12px;margin-top:8px;border:1.5px solid #bfe8e3;background:#effaf8;color:#0f766e}',
    '.sc-btn:active{transform:scale(.97)}',
    '.sc-btn--primary{background:var(--grad-btn);color:#fff;border:none;box-shadow:0 2px 8px rgba(15,118,110,.28)}',
    '.sc-btn:disabled{opacity:.55}',
    '.sc-cancel-link{display:block;text-align:center;font-size:16px;color:#5b6670;text-decoration:underline;padding:12px 0;min-height:48px}',
    '.sc-status{background:var(--well);border:1px solid var(--hairline);border-radius:12px;padding:12px;margin-top:8px}',
    '.sc-msg{font-size:16px;line-height:1.6;border-radius:12px;padding:12px;margin-top:8px;background:#effaf8;border:1px solid #bfe8e3;color:#052422;white-space:pre-line}',
    '.sc-msg--warn{background:#fff7ed;border-color:#fed7aa;color:#7c2d12}',
    '.sc-date-input{min-height:48px;font-size:16px;border:1.5px solid var(--hairline);border-radius:12px;padding:8px 12px;width:100%;margin-top:8px;background:#fff;color:#052422}',
    '.sc-state-chip{display:inline-block;font-size:14px;font-weight:700;border-radius:999px;padding:2px 10px;background:var(--well);color:#3f4b55;margin-left:8px}',
  ].join('\n    ');
}

/**
 * client JS 本体。liff-pages.ts が gate on のとき inlineScriptBody() を通して emit する。
 * 依存 (esc / apiGet / API_BASE / idToken / showToast / apiFailed) は本体 script の関数を使う。
 */
export function subCardJs(): string {
  return SUB_CARD_JS;
}

// 通常の string 連結で保持する (TS template literal のエスケープ潰れ事故を構造的に避ける)。
const SUB_CARD_JS: string = [
  "// ─── 定期便のお手続きカード (Ultraplan PR-5, gate LIFF_SUB_CARD_ENABLED) ───",
  "var __subContractsLoaded = false;",
  "var __scData = null; // 直近の GET 応答 (再描画・cycleKey 参照用)",
  "",
  "function loadSubContractsOnce() {",
  "  if (__subContractsLoaded) return;",
  "  __subContractsLoaded = true;",
  "  loadSubContracts();",
  "}",
  "",
  "// 戻り値: カードを描画・表示できたか。false = 呼び出し側は sc-msg でなく toast へ",
  "// フォールバックする (非表示カード配下への書き込みは誰にも見えない)。",
  "async function loadSubContracts() {",
  "  var card = document.getElementById('sub-contracts-card');",
  "  if (!card) return false;",
  "  try {",
  "    var res = await apiGet('/api/liff/sub-contracts');",
  "    // 失敗時は非表示のまま (shop タブの他カードに影響させない。401 は apiGet 中央検知)",
  "    if (apiFailed(res) || !res.data) { card.style.display = 'none'; return false; }",
  "    __scData = res.data;",
  "    scRender(res.data);",
  "    return card.style.display === 'block';",
  "  } catch (e) { card.style.display = 'none'; return false; }",
  "}",
  "",
  "function scRender(data) {",
  "  var card = document.getElementById('sub-contracts-card');",
  "  var list = document.getElementById('sub-contracts-list');",
  "  if (!card || !list) return;",
  "  // gate off / 未連携 / 契約なし → カードごと出さない (空 chrome を見せない)。",
  "  // 解約済み契約も出さない (見せ続けるのは 60代に不安を与えるだけ)。",
  "  var contracts = (data && data.enabled && data.linked && data.contracts) ? data.contracts.filter(function (c) { return c.state !== 'cancelled'; }) : [];",
  "  if (!contracts.length) { card.style.display = 'none'; return; }",
  "  var html = '';",
  "  for (var i = 0; i < contracts.length; i++) {",
  "    html += scItemHtml(contracts[i], i, data.subIntentEnabled === true);",
  "  }",
  "  list.innerHTML = html;",
  "  card.style.display = 'block';",
  "}",
  "",
  "// 1 契約ぶんの描画。ボタンは最大 3 (skip/date/pause)、解約はテキストリンク (§7)。",
  "function scItemHtml(c, idx, intentOn) {",
  "  var stateChip = c.state === 'paused' ? '<span class=\"sc-state-chip\">一時停止中</span>' : '';",
  "  var html = '<div class=\"sc-item\" id=\"sc-item-' + idx + '\">' +",
  "    '<p class=\"sc-plan\">' + esc(c.planName || '定期便') + stateChip + '</p>' +",
  "    (c.presentableDate ? '<p class=\"sc-body\">次回の決済予定 (お届けはその2〜4日後ごろ)</p><p class=\"sc-date\">' + esc(scJpDate(c.presentableDate)) + 'ごろ</p>' : '<p class=\"sc-body\">次回の決済予定日は確認中です</p>') +",
  "    (c.deadlineText ? '<p class=\"sc-deadline\">' + esc(c.deadlineText) + '</p>' : '');",
  "  var intents = c.openIntents || [];",
  "  if (intents.length) {",
  "    // 受理済み: 状況 + [取り消す] (§1-3)。新しいボタンは出さない (二重依頼の温床)。",
  "    // undo POST は SUB_INTENT_ENABLED も要求する — 受理レイヤーが閉じている間は",
  "    // 必ず失敗するボタンを出さず (§1)、相談導線に降格する",
  "    for (var i = 0; i < intents.length; i++) {",
  "      var it = intents[i];",
  "      html += '<div class=\"sc-status\">' +",
  "        '<p class=\"sc-body\">「' + esc(it.opLabel) + '」のご依頼を承りました' + (it.requestedDate ? ' (' + esc(scJpDate(it.requestedDate)) + ')' : '') + '</p>' +",
  "        (it.promisedBy ? '<p class=\"sc-deadline\">' + esc(scPromiseText(it.promisedBy)) + '</p>' : '') +",
  "        (intentOn",
  "          ? '<button class=\"tap sc-btn\" data-intent=\"' + esc(it.id) + '\" onclick=\"scUndo(this)\">このご依頼を取り消す</button>'",
  "          : '<p class=\"sc-body\">取り消しのご希望は、LINE のトークルームでどうぞ🌿</p>') +",
  "        '</div>';",
  "    }",
  "  } else if (intentOn && c.state === 'active') {",
  "    // §3: skip の 1 タップは「押す前に結果日付が読める」が唯一の成立条件。",
  "    //   derived 推定なので「ごろ」必須 (§3-2)。日付を計算できないときは捏造せず fallback 文言",
  "    var skipNext = scAddDays(c.presentableDate, c.intervalDays);",
  "    html += (skipNext",
  "      ? '<p class=\"sc-date\">押すと 次回は ' + esc(scJpDate(skipNext)) + 'ごろ になるお申し込みになります</p>'",
  "      : '<p class=\"sc-body\">押すと、次回分をお休みするお申し込みになります (次のお届け予定はマイページでご確認ください)</p>') +",
  "      '<button class=\"tap sc-btn\" data-op=\"skip\" data-idx=\"' + idx + '\" onclick=\"scAct(this)\">今回はスキップする</button>' +",
  "      '<button class=\"tap sc-btn\" data-op=\"date\" data-idx=\"' + idx + '\" onclick=\"scAct(this)\">お届け日を変更する</button>' +",
  "      '<button class=\"tap sc-btn\" data-op=\"pause\" data-idx=\"' + idx + '\" onclick=\"scAct(this)\">しばらくお休みする</button>' +",
  "      '<a href=\"javascript:void(0)\" class=\"tap sc-cancel-link\" data-op=\"cancel\" data-idx=\"' + idx + '\" onclick=\"scAct(this)\">解約のお手続きはこちら</a>';",
  "  } else if (intentOn && c.state === 'paused') {",
  "    // 停止中は cancel だけ受理できる (API §1-2)。再開はトークへ",
  "    html += '<p class=\"sc-body\">再開のご希望は、LINE のトークルームでいつでもどうぞ🌿</p>' +",
  "      '<a href=\"javascript:void(0)\" class=\"tap sc-cancel-link\" data-op=\"cancel\" data-idx=\"' + idx + '\" onclick=\"scAct(this)\">解約のお手続きはこちら</a>';",
  "  } else {",
  "    // 受理レイヤー未開放: 実行できないボタンを出さない (§1)。相談導線だけ",
  "    html += '<p class=\"sc-body\">お手続きのご希望は、LINE のトークルームでお気軽にどうぞ🌿</p>';",
  "  }",
  "  html += '<div id=\"sc-panel-' + idx + '\"></div><div id=\"sc-msg-' + idx + '\"></div></div>';",
  "  return html;",
  "}",
  "",
  "// YYYY-MM-DD + N日 (UTC 固定)。どちらかが不正なら null (日付を捏造しない)",
  "function scAddDays(ymd, days) {",
  "  var m = /^([0-9]{4})-([0-9]{2})-([0-9]{2})$/.exec(String(ymd || ''));",
  "  var n = Number(days);",
  "  if (!m || !isFinite(n) || n <= 0) return null;",
  "  var t = Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3])) + n * 86400000;",
  "  return new Date(t).toISOString().slice(0, 10);",
  "}",
  "",
  "// YYYY-MM-DD → M月D日 (壊れた値はそのまま返す — 嘘の日付を作らない)",
  "function scJpDate(s) {",
  "  var m = /^([0-9]{4})-([0-9]{2})-([0-9]{2})/.exec(String(s || ''));",
  "  if (!m) return String(s || '');",
  "  return Number(m[2]) + '月' + Number(m[3]) + '日';",
  "}",
  "",
  "function scPromiseText(promisedBy) {",
  "  var s = String(promisedBy || '').slice(0, 16).replace('T', ' ');",
  "  return s ? s + ' までにスタッフが対応し、結果を必ずご連絡いたします' : '';",
  "}",
  "",
  "function scContractAt(idx) {",
  "  var contracts = (__scData && __scData.contracts) ? __scData.contracts.filter(function (c) { return c.state !== 'cancelled'; }) : [];",
  "  return contracts[Number(idx)] || null;",
  "}",
  "",
  "function scShowMsg(idx, text, warn) {",
  "  var el = document.getElementById('sc-msg-' + idx);",
  "  if (!el) { showToast(text); return; }",
  "  el.innerHTML = '<div class=\"sc-msg' + (warn ? ' sc-msg--warn' : '') + '\">' + esc(text) + '</div>';",
  "}",
  "",
  "// ボタン起点の分岐。date は選択パネル、cancel は確認パネル (どちらも 2 タップ目で送信 §2)",
  "function scAct(btn) {",
  "  var op = btn.getAttribute('data-op');",
  "  var idx = btn.getAttribute('data-idx');",
  "  var c = scContractAt(idx);",
  "  if (!c) return;",
  "  if (op === 'date') { scShowDatePanel(idx); return; }",
  "  if (op === 'cancel') { scShowCancelPanel(idx); return; }",
  "  return scSubmit(idx, op, null, false, btn);",
  "}",
  "",
  "function scShowDatePanel(idx) {",
  "  var panel = document.getElementById('sc-panel-' + idx);",
  "  if (!panel) return;",
  "  // min = 明日 (JST)。サーバ側でも同じ検証をする — picker は防壁ではない",
  "  var t = new Date(Date.now() + 9 * 3600000 + 86400000);",
  "  var min = t.toISOString().slice(0, 10);",
  "  panel.innerHTML = '<input type=\"date\" class=\"sc-date-input\" id=\"sc-date-' + idx + '\" min=\"' + min + '\">' +",
  "    '<button class=\"tap sc-btn sc-btn--primary\" data-idx=\"' + idx + '\" onclick=\"scSubmitDate(this)\">この日に変更を依頼する</button>' +",
  "    '<button class=\"tap sc-btn\" data-idx=\"' + idx + '\" onclick=\"scClearPanel(this)\">やめておく</button>';",
  "}",
  "",
  "function scShowCancelPanel(idx) {",
  "  var panel = document.getElementById('sc-panel-' + idx);",
  "  if (!panel) return;",
  "  panel.innerHTML = '<div class=\"sc-msg sc-msg--warn\">解約のご依頼を送ります。よろしいですか?\\n(スタッフが確認のうえ対応し、結果を必ずご連絡いたします)</div>' +",
  "    '<button class=\"tap sc-btn sc-btn--primary\" data-idx=\"' + idx + '\" onclick=\"scSubmitCancel(this)\">解約を依頼する</button>' +",
  "    '<button class=\"tap sc-btn\" data-idx=\"' + idx + '\" onclick=\"scClearPanel(this)\">やめておく</button>';",
  "}",
  "",
  "function scClearPanel(btn) {",
  "  var panel = document.getElementById('sc-panel-' + btn.getAttribute('data-idx'));",
  "  if (panel) panel.innerHTML = '';",
  "}",
  "",
  "function scSubmitDate(btn) {",
  "  var idx = btn.getAttribute('data-idx');",
  "  var input = document.getElementById('sc-date-' + idx);",
  "  var v = input && input.value ? String(input.value) : '';",
  "  if (!v) { scShowMsg(idx, 'お日にちをお選びください', true); return; }",
  "  return scSubmit(idx, 'date', v, false, btn);",
  "}",
  "",
  "function scSubmitCancel(btn) {",
  "  return scSubmit(btn.getAttribute('data-idx'), 'cancel', null, false, btn);",
  "}",
  "",
  "// §4-1 late_promise の ack 再送 (開示済みの同 op を data-* で運ぶ)",
  "function scAckResend(btn) {",
  "  return scSubmit(btn.getAttribute('data-idx'), btn.getAttribute('data-op'), btn.getAttribute('data-date') || null, true, btn);",
  "}",
  "",
  "async function scSubmit(idx, op, requestedDate, ack, btn) {",
  "  var c = scContractAt(idx);",
  "  if (!c) return;",
  "  if (btn) btn.disabled = true; // 連打防止 (受理は冪等だが duplicate 文言を出さない)",
  "  try {",
  "    var body = { op: op, cycleKey: c.cycleKey };",
  "    if (requestedDate) body.requestedDate = requestedDate;",
  "    if (ack) body.ack = true;",
  "    var res = await fetch(API_BASE + '/api/liff/sub-contracts/' + encodeURIComponent(c.contractId) + '/intents', {",
  "      method: 'POST',",
  "      headers: { 'Content-Type': 'application/json', ...(idToken ? { Authorization: 'Bearer ' + idToken } : {}) },",
  "      body: JSON.stringify(body),",
  "    });",
  "    var json = await res.json().catch(function () { return null; });",
  "    if (res.status === 401) { handleAuthExpired(); return; }",
  "    if (json && json.success && json.data) {",
  "      // accepted / duplicate — 最新状態を引き直してから、サーバの文言をそのまま見せる (§1)。",
  "      // 順序が逆だと再描画が message を消す (sc-msg は list ごと innerHTML で作り直されるため)。",
  "      // 再取得に失敗した場合はカードが非表示になる — 受理済みの事実 (§4-1 の約束と",
  "      // cancel の救済手順を含む文言) を見えない場所に書かず toast へフォールバックする",
  "      var shown = await loadSubContracts();",
  "      var okMsg = (json.data.message || 'ご依頼を承りました。');",
  "      if (shown) { scShowMsg(idx, okMsg, false); } else { showToast(okMsg); }",
  "      return;",
  "    }",
  "    var err = json && json.error;",
  "    if (err === 'late_promise') {",
  "      // §4-1: 受理していない。開示して顧客に選ばせる",
  "      var panel = document.getElementById('sc-panel-' + idx);",
  "      if (panel) {",
  "        panel.innerHTML = '<div class=\"sc-msg sc-msg--warn\">' + esc(json.disclosure || '対応が次回決済の後になる可能性があります。') + '</div>' +",
  "          '<button class=\"tap sc-btn sc-btn--primary\" data-idx=\"' + idx + '\" data-op=\"' + esc(op) + '\"' + (requestedDate ? ' data-date=\"' + esc(requestedDate) + '\"' : '') + ' onclick=\"scAckResend(this)\">それでもお願いする</button>' +",
  "          '<button class=\"tap sc-btn\" data-idx=\"' + idx + '\" onclick=\"scClearPanel(this)\">やめておく</button>';",
  "      }",
  "      return;",
  "    }",
  "    if (err === 'cycle_changed') {",
  "      // 再描画 → メッセージの順 (accepted 分岐と同じ不変条件 — 逆順は再描画が消す)",
  "      var reShown = await loadSubContracts();",
  "      var cycleMsg = 'お届け予定が更新されていたため、最新の情報に更新しました。お手数ですがもう一度お選びください。';",
  "      if (reShown) { scShowMsg(idx, cycleMsg, true); } else { showToast(cycleMsg); }",
  "      return;",
  "    }",
  "    // deadline_passed / contract_inactive / paused_op_unavailable / gate_off / validation",
  "    scShowMsg(idx, (json && (json.message || json.error)) || 'お手続きを受け付けられませんでした。時間をおいてお試しください', true);",
  "  } catch (e) {",
  "    scShowMsg(idx, '通信に失敗しました。電波の良いところでもう一度お試しください', true);",
  "  } finally {",
  "    if (btn) btn.disabled = false;",
  "  }",
  "}",
  "",
  "async function scUndo(btn) {",
  "  var intentId = btn.getAttribute('data-intent');",
  "  if (!intentId) return;",
  "  btn.disabled = true;",
  "  try {",
  "    var res = await fetch(API_BASE + '/api/liff/sub-intents/' + encodeURIComponent(intentId) + '/undo', {",
  "      method: 'POST',",
  "      headers: { 'Content-Type': 'application/json', ...(idToken ? { Authorization: 'Bearer ' + idToken } : {}) },",
  "      body: '{}',",
  "    });",
  "    var json = await res.json().catch(function () { return null; });",
  "    if (res.status === 401) { handleAuthExpired(); return; }",
  "    if (json && json.success && json.data) {",
  "      showToast(json.data.status === 'cancelled' ? 'ご依頼を取り消しました' : '取り消しのご依頼を承りました');",
  "      await loadSubContracts();",
  "      return;",
  "    }",
  "    if (json && json.error === 'not_undoable') {",
  "      showToast('このご依頼は対応が進んでいるため、この画面からは取り消せません。トークルームでご相談ください');",
  "      await loadSubContracts();",
  "      return;",
  "    }",
  "    // gate_off 等はサーバの message (マイページ誘導) をそのまま見せる — 「時間をおいて」",
  "    // では絶対に成功しない操作へ誤誘導しない",
  "    showToast((json && (json.message || json.error)) || '取り消しを受け付けられませんでした。時間をおいてお試しください');",
  "  } catch (e) {",
  "    showToast('通信に失敗しました。もう一度お試しください');",
  "  } finally {",
  "    btn.disabled = false;",
  "  }",
  "}",
].join('\n');
