-- LINE OSS CRM D1 Schema
-- IDs are TEXT and generated by app code using crypto.randomUUID()

-- ============================================================
-- Friends
-- ============================================================
CREATE TABLE IF NOT EXISTS friends (
  id               TEXT PRIMARY KEY,
  line_user_id     TEXT UNIQUE NOT NULL,
  display_name     TEXT,
  picture_url      TEXT,
  status_message   TEXT,
  is_following     INTEGER NOT NULL DEFAULT 1,
  user_id          TEXT,
  score            INTEGER NOT NULL DEFAULT 0,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),

  ref_code             TEXT,
  metadata             TEXT NOT NULL DEFAULT '{}',
  line_account_id      TEXT REFERENCES line_accounts(id),
  gender               TEXT,
  birthday             TEXT,
  first_purchase_date  TEXT,
  preferred_language   TEXT DEFAULT 'ja' CHECK (preferred_language IN ('ja', 'en', 'ko', 'zh', 'th')),
  is_blacklisted       INTEGER NOT NULL DEFAULT 0,
  status               TEXT NOT NULL DEFAULT 'none',
  phone                TEXT,
  email                TEXT,
  address              TEXT,
  memo                 TEXT,
  assigned_staff_id    TEXT REFERENCES staff_members(id) ON DELETE SET NULL);

CREATE INDEX IF NOT EXISTS idx_friends_line_user_id ON friends (line_user_id);
CREATE INDEX IF NOT EXISTS idx_friends_user_id ON friends (user_id);

-- ============================================================
-- Tags
-- ============================================================
CREATE TABLE IF NOT EXISTS tags (
  id         TEXT PRIMARY KEY,
  name       TEXT UNIQUE NOT NULL,
  color      TEXT NOT NULL DEFAULT '#3B82F6',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Friend <-> Tag join
-- ============================================================
CREATE TABLE IF NOT EXISTS friend_tags (
  friend_id   TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  tag_id      TEXT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
  assigned_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  PRIMARY KEY (friend_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_friend_tags_tag_id ON friend_tags (tag_id);

-- ============================================================
-- Scenarios
-- ============================================================
CREATE TABLE IF NOT EXISTS scenarios (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  description     TEXT,
  trigger_type    TEXT NOT NULL CHECK (trigger_type IN ('friend_add', 'tag_added', 'manual')),
  trigger_tag_id  TEXT REFERENCES tags (id) ON DELETE SET NULL,
  is_active       INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),

  line_account_id      TEXT);

-- ============================================================
-- Scenario Steps
-- ============================================================
CREATE TABLE IF NOT EXISTS scenario_steps (
  id              TEXT PRIMARY KEY,
  scenario_id     TEXT NOT NULL REFERENCES scenarios (id) ON DELETE CASCADE,
  step_order      INTEGER NOT NULL,
  delay_minutes   INTEGER NOT NULL DEFAULT 0,
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex')),
  message_content TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  condition_type       TEXT,
  condition_value      TEXT,
  next_step_on_false   INTEGER,
  UNIQUE (scenario_id, step_order)
);

CREATE INDEX IF NOT EXISTS idx_scenario_steps_scenario_id ON scenario_steps (scenario_id);

-- ============================================================
-- Friend Scenario Enrollments
-- ============================================================
CREATE TABLE IF NOT EXISTS friend_scenarios (
  id                 TEXT PRIMARY KEY,
  friend_id          TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  scenario_id        TEXT NOT NULL REFERENCES scenarios (id) ON DELETE CASCADE,
  current_step_order INTEGER NOT NULL DEFAULT 0,
  status             TEXT NOT NULL CHECK (status IN ('active', 'paused', 'completed')) DEFAULT 'active',
  started_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  next_delivery_at   TEXT,
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friend_scenarios_next_delivery_at ON friend_scenarios (next_delivery_at);
CREATE INDEX IF NOT EXISTS idx_friend_scenarios_status ON friend_scenarios (status);
CREATE INDEX IF NOT EXISTS idx_friend_scenarios_friend_id ON friend_scenarios (friend_id);

-- ============================================================
-- Broadcasts
-- ============================================================
CREATE TABLE IF NOT EXISTS broadcasts (
  id              TEXT PRIMARY KEY,
  title           TEXT NOT NULL,
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex')),
  message_content TEXT NOT NULL,
  target_type     TEXT NOT NULL CHECK (target_type IN ('all', 'tag')) DEFAULT 'all',
  target_tag_id   TEXT REFERENCES tags (id) ON DELETE SET NULL,
  status          TEXT NOT NULL CHECK (status IN ('draft', 'scheduled', 'sending', 'sent')) DEFAULT 'draft',
  scheduled_at    TEXT,
  sent_at         TEXT,
  total_count     INTEGER NOT NULL DEFAULT 0,
  success_count   INTEGER NOT NULL DEFAULT 0,
  line_request_id TEXT,
  insights_json   TEXT,
  insights_fetched_at TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),

  line_account_id      TEXT,
  alt_text             TEXT);

CREATE INDEX IF NOT EXISTS idx_broadcasts_status ON broadcasts (status);
CREATE INDEX IF NOT EXISTS idx_broadcasts_line_request_id ON broadcasts (line_request_id);

-- ============================================================
-- Messages Log
-- ============================================================
CREATE TABLE IF NOT EXISTS messages_log (
  id               TEXT PRIMARY KEY,
  friend_id        TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  direction        TEXT NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
  message_type     TEXT NOT NULL,
  content          TEXT NOT NULL,
  broadcast_id     TEXT REFERENCES broadcasts (id) ON DELETE SET NULL,
  scenario_step_id TEXT REFERENCES scenario_steps (id) ON DELETE SET NULL,
  delivery_type    TEXT CHECK (delivery_type IN ('push', 'reply')),
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),

  ab_test_id           TEXT REFERENCES ab_tests (id) ON DELETE SET NULL);

CREATE INDEX IF NOT EXISTS idx_messages_log_friend_id ON messages_log (friend_id);
CREATE INDEX IF NOT EXISTS idx_messages_log_created_at ON messages_log (created_at);

-- ============================================================
-- Auto Replies
-- ============================================================
CREATE TABLE IF NOT EXISTS auto_replies (
  id               TEXT PRIMARY KEY,
  keyword          TEXT NOT NULL,
  match_type       TEXT NOT NULL CHECK (match_type IN ('exact', 'contains')) DEFAULT 'exact',
  response_type    TEXT NOT NULL DEFAULT 'text',
  response_content TEXT NOT NULL,
  is_active        INTEGER NOT NULL DEFAULT 1,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Admin Users
-- ============================================================
CREATE TABLE IF NOT EXISTS admin_users (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 2: Internal UUID Users (Cross-Account)
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id           TEXT PRIMARY KEY,
  email        TEXT,
  phone        TEXT,
  external_id  TEXT,
  display_name TEXT,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS idx_users_external_id ON users (external_id);

-- ============================================================
-- Round 2: LINE Account Management (Multi-Account)
-- ============================================================
CREATE TABLE IF NOT EXISTS line_accounts (
  id                   TEXT PRIMARY KEY,
  channel_id           TEXT NOT NULL UNIQUE,
  name                 TEXT NOT NULL,
  channel_access_token TEXT NOT NULL,
  channel_secret       TEXT NOT NULL,
  is_active            INTEGER NOT NULL DEFAULT 1,
  created_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),

  login_channel_id     TEXT,
  login_channel_secret TEXT,
  liff_id              TEXT,
  token_expires_at     TEXT,
  bot_user_id          TEXT);

-- ============================================================
-- Round 2: Conversion Points (CV Tracking)
-- ============================================================
CREATE TABLE IF NOT EXISTS conversion_points (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  event_type TEXT NOT NULL,
  value      REAL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 2: Conversion Events (CV Records)
-- ============================================================
CREATE TABLE IF NOT EXISTS conversion_events (
  id                  TEXT PRIMARY KEY,
  conversion_point_id TEXT NOT NULL REFERENCES conversion_points (id) ON DELETE CASCADE,
  friend_id           TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  user_id             TEXT,
  affiliate_code      TEXT,
  metadata            TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_conversion_events_point ON conversion_events (conversion_point_id);
CREATE INDEX IF NOT EXISTS idx_conversion_events_friend ON conversion_events (friend_id);
CREATE INDEX IF NOT EXISTS idx_conversion_events_affiliate ON conversion_events (affiliate_code);

-- ============================================================
-- Round 2: Affiliates
-- ============================================================
CREATE TABLE IF NOT EXISTS affiliates (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  code            TEXT NOT NULL UNIQUE,
  commission_rate REAL NOT NULL DEFAULT 0,
  is_active       INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 2: Affiliate Clicks
-- ============================================================
CREATE TABLE IF NOT EXISTS affiliate_clicks (
  id           TEXT PRIMARY KEY,
  affiliate_id TEXT NOT NULL REFERENCES affiliates (id) ON DELETE CASCADE,
  url          TEXT,
  ip_address   TEXT,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_affiliate ON affiliate_clicks (affiliate_id);

-- ============================================================
-- Round 3: Webhook IN/OUT
-- ============================================================
CREATE TABLE IF NOT EXISTS incoming_webhooks (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'custom',
  secret      TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS outgoing_webhooks (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  url         TEXT NOT NULL,
  event_types TEXT NOT NULL DEFAULT '[]',
  secret      TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 3: Google Calendar
-- ============================================================
CREATE TABLE IF NOT EXISTS google_calendar_connections (
  id            TEXT PRIMARY KEY,
  calendar_id   TEXT NOT NULL,
  access_token  TEXT,
  refresh_token TEXT,
  api_key       TEXT,
  auth_type     TEXT NOT NULL DEFAULT 'api_key',
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS calendar_bookings (
  id             TEXT PRIMARY KEY,
  connection_id  TEXT NOT NULL REFERENCES google_calendar_connections (id) ON DELETE CASCADE,
  friend_id      TEXT REFERENCES friends (id) ON DELETE SET NULL,
  event_id       TEXT,
  title          TEXT NOT NULL,
  start_at       TEXT NOT NULL,
  end_at         TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'cancelled', 'completed')),
  metadata       TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_calendar_bookings_friend ON calendar_bookings (friend_id);
CREATE INDEX IF NOT EXISTS idx_calendar_bookings_start ON calendar_bookings (start_at);

-- ============================================================
-- Round 3: リマインダ配信
-- ============================================================
CREATE TABLE IF NOT EXISTS reminders (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),

  line_account_id      TEXT);

CREATE TABLE IF NOT EXISTS reminder_steps (
  id              TEXT PRIMARY KEY,
  reminder_id     TEXT NOT NULL REFERENCES reminders (id) ON DELETE CASCADE,
  offset_minutes  INTEGER NOT NULL,
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex')),
  message_content TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_reminder_steps_reminder ON reminder_steps (reminder_id);

CREATE TABLE IF NOT EXISTS friend_reminders (
  id              TEXT PRIMARY KEY,
  friend_id       TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  reminder_id     TEXT NOT NULL REFERENCES reminders (id) ON DELETE CASCADE,
  target_date     TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friend_reminders_status ON friend_reminders (status);
CREATE INDEX IF NOT EXISTS idx_friend_reminders_friend ON friend_reminders (friend_id);

CREATE TABLE IF NOT EXISTS friend_reminder_deliveries (
  id                TEXT PRIMARY KEY,
  friend_reminder_id TEXT NOT NULL REFERENCES friend_reminders (id) ON DELETE CASCADE,
  reminder_step_id  TEXT NOT NULL REFERENCES reminder_steps (id) ON DELETE CASCADE,
  delivered_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (friend_reminder_id, reminder_step_id)
);

-- ============================================================
-- Round 3: スコアリング
-- ============================================================
CREATE TABLE IF NOT EXISTS scoring_rules (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  event_type  TEXT NOT NULL,
  score_value INTEGER NOT NULL,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS friend_scores (
  id              TEXT PRIMARY KEY,
  friend_id       TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  scoring_rule_id TEXT REFERENCES scoring_rules (id) ON DELETE SET NULL,
  score_change    INTEGER NOT NULL,
  reason          TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friend_scores_friend ON friend_scores (friend_id);
CREATE INDEX IF NOT EXISTS idx_friend_scores_created ON friend_scores (created_at);

-- ============================================================
-- Round 3: テンプレート管理
-- ============================================================
CREATE TABLE IF NOT EXISTS templates (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  category        TEXT NOT NULL DEFAULT 'general',
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex', 'carousel')),
  message_content TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_templates_category ON templates (category);

-- ============================================================
-- Round 3: オペレーター/チャット
-- ============================================================
CREATE TABLE IF NOT EXISTS operators (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT NOT NULL UNIQUE,
  role       TEXT NOT NULL DEFAULT 'operator' CHECK (role IN ('admin', 'operator')),
  is_active  INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS chats (
  id            TEXT PRIMARY KEY,
  friend_id     TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  operator_id   TEXT REFERENCES operators (id) ON DELETE SET NULL,
  status        TEXT NOT NULL DEFAULT 'unread' CHECK (status IN ('unread', 'in_progress', 'resolved')),
  notes         TEXT,
  last_message_at TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),

  line_account_id      TEXT);

CREATE INDEX IF NOT EXISTS idx_chats_friend ON chats (friend_id);
CREATE INDEX IF NOT EXISTS idx_chats_operator ON chats (operator_id);
CREATE INDEX IF NOT EXISTS idx_chats_status ON chats (status);

-- ============================================================
-- Round 3: 通知機能
-- ============================================================
CREATE TABLE IF NOT EXISTS notification_rules (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  event_type   TEXT NOT NULL,
  conditions   TEXT NOT NULL DEFAULT '{}',
  channels     TEXT NOT NULL DEFAULT '["webhook"]',
  is_active    INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS notifications (
  id              TEXT PRIMARY KEY,
  rule_id         TEXT REFERENCES notification_rules (id) ON DELETE SET NULL,
  event_type      TEXT NOT NULL,
  title           TEXT NOT NULL,
  body            TEXT NOT NULL,
  channel         TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
  metadata        TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_notifications_status ON notifications (status);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications (created_at);

-- ============================================================
-- Round 3: Stripe決済連携
-- ============================================================
CREATE TABLE IF NOT EXISTS stripe_events (
  id               TEXT PRIMARY KEY,
  stripe_event_id  TEXT NOT NULL UNIQUE,
  event_type       TEXT NOT NULL,
  friend_id        TEXT REFERENCES friends (id) ON DELETE SET NULL,
  amount           REAL,
  currency         TEXT,
  metadata         TEXT,
  processed_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_stripe_events_friend ON stripe_events (friend_id);
CREATE INDEX IF NOT EXISTS idx_stripe_events_type ON stripe_events (event_type);

-- ============================================================
-- Round 3: BAN検知 & リカバリ
-- ============================================================
CREATE TABLE IF NOT EXISTS account_health_logs (
  id              TEXT PRIMARY KEY,
  line_account_id TEXT NOT NULL,
  error_code      INTEGER,
  error_count     INTEGER NOT NULL DEFAULT 0,
  check_period    TEXT NOT NULL,
  risk_level      TEXT NOT NULL DEFAULT 'normal' CHECK (risk_level IN ('normal', 'warning', 'danger')),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_health_logs_account ON account_health_logs (line_account_id);

CREATE TABLE IF NOT EXISTS account_migrations (
  id               TEXT PRIMARY KEY,
  from_account_id  TEXT NOT NULL,
  to_account_id    TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'failed')),
  migrated_count   INTEGER NOT NULL DEFAULT 0,
  total_count      INTEGER NOT NULL DEFAULT 0,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  completed_at     TEXT
);

-- ============================================================
-- Round 3: アクション自動化
-- ============================================================
CREATE TABLE IF NOT EXISTS automations (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  event_type  TEXT NOT NULL,
  conditions  TEXT NOT NULL DEFAULT '{}',
  actions     TEXT NOT NULL DEFAULT '[]',
  is_active   INTEGER NOT NULL DEFAULT 1,
  priority    INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),

  line_account_id      TEXT);

CREATE INDEX IF NOT EXISTS idx_automations_event ON automations (event_type);
CREATE INDEX IF NOT EXISTS idx_automations_active ON automations (is_active);

CREATE TABLE IF NOT EXISTS automation_logs (
  id             TEXT PRIMARY KEY,
  automation_id  TEXT NOT NULL REFERENCES automations (id) ON DELETE CASCADE,
  friend_id      TEXT REFERENCES friends (id) ON DELETE SET NULL,
  event_data     TEXT,
  actions_result TEXT,
  status         TEXT NOT NULL DEFAULT 'success' CHECK (status IN ('success', 'partial', 'failed')),
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_automation_logs_automation ON automation_logs (automation_id);

-- ============================================================
-- Ad Platform Configuration
-- ============================================================
CREATE TABLE IF NOT EXISTS ad_platforms (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  display_name TEXT,
  config       TEXT NOT NULL DEFAULT '{}',
  is_active    INTEGER DEFAULT 1,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Ad Conversion Logs
-- ============================================================
CREATE TABLE IF NOT EXISTS ad_conversion_logs (
  id                  TEXT PRIMARY KEY,
  ad_platform_id      TEXT NOT NULL,
  friend_id           TEXT NOT NULL,
  conversion_point_id TEXT,
  event_name          TEXT NOT NULL,
  click_id            TEXT,
  click_id_type       TEXT,
  status              TEXT DEFAULT 'pending',
  request_body        TEXT,
  response_body       TEXT,
  error_message       TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_ad_conversion_logs_platform ON ad_conversion_logs (ad_platform_id);
CREATE INDEX IF NOT EXISTS idx_ad_conversion_logs_friend ON ad_conversion_logs (friend_id);
CREATE INDEX IF NOT EXISTS idx_ad_conversion_logs_status ON ad_conversion_logs (status);

-- Staff member accounts with role-based access control
CREATE TABLE IF NOT EXISTS staff_members (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT,
  role       TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'staff')),
  api_key    TEXT UNIQUE NOT NULL,
  is_active  INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_members_api_key ON staff_members(api_key);
CREATE INDEX IF NOT EXISTS idx_staff_members_role ON staff_members(role);

-- ============================================================
-- AUTO-APPENDED from migrations/*.sql
-- Regenerated by scripts/regenerate-schema.mjs
-- Do NOT edit this section by hand; rerun the script instead.
-- ============================================================

-- from 003_entry_routes.sql
CREATE TABLE IF NOT EXISTS entry_routes (
  id          TEXT PRIMARY KEY,
  ref_code    TEXT UNIQUE NOT NULL,
  name        TEXT NOT NULL,
  tag_id      TEXT REFERENCES tags (id) ON DELETE SET NULL,
  scenario_id TEXT REFERENCES scenarios (id) ON DELETE SET NULL,
  redirect_url TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- from 003_entry_routes.sql
CREATE TABLE IF NOT EXISTS ref_tracking (
  id              TEXT PRIMARY KEY,
  ref_code        TEXT NOT NULL,
  friend_id       TEXT REFERENCES friends (id) ON DELETE CASCADE,
  entry_route_id  TEXT REFERENCES entry_routes (id) ON DELETE SET NULL,
  source_url      TEXT,
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- from 006_tracked_links.sql
CREATE TABLE IF NOT EXISTS tracked_links (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  original_url TEXT NOT NULL,
  tag_id TEXT REFERENCES tags (id) ON DELETE SET NULL,
  scenario_id TEXT REFERENCES scenarios (id) ON DELETE SET NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  click_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- from 006_tracked_links.sql
CREATE TABLE IF NOT EXISTS link_clicks (
  id TEXT PRIMARY KEY,
  tracked_link_id TEXT NOT NULL REFERENCES tracked_links (id) ON DELETE CASCADE,
  friend_id TEXT REFERENCES friends (id) ON DELETE SET NULL,
  clicked_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- from 007_forms.sql
CREATE TABLE IF NOT EXISTS forms (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  fields TEXT NOT NULL DEFAULT '[]',
  on_submit_tag_id TEXT REFERENCES tags (id) ON DELETE SET NULL,
  on_submit_scenario_id TEXT REFERENCES scenarios (id) ON DELETE SET NULL,
  save_to_metadata INTEGER NOT NULL DEFAULT 1,
  is_active INTEGER NOT NULL DEFAULT 1,
  submit_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- from 007_forms.sql
CREATE TABLE IF NOT EXISTS form_submissions (
  id TEXT PRIMARY KEY,
  form_id TEXT NOT NULL REFERENCES forms (id) ON DELETE CASCADE,
  friend_id TEXT REFERENCES friends (id) ON DELETE SET NULL,
  data TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- from 014_shopify.sql
CREATE TABLE IF NOT EXISTS shopify_orders (
  id TEXT PRIMARY KEY,
  shopify_order_id TEXT NOT NULL UNIQUE,
  shopify_customer_id TEXT,
  friend_id TEXT REFERENCES friends(id) ON DELETE SET NULL,
  email TEXT,
  phone TEXT,
  total_price REAL,
  currency TEXT DEFAULT 'JPY',
  financial_status TEXT,
  fulfillment_status TEXT,
  order_number INTEGER,
  line_items TEXT,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 014_shopify.sql
CREATE TABLE IF NOT EXISTS shopify_customers (
  id TEXT PRIMARY KEY,
  shopify_customer_id TEXT NOT NULL UNIQUE,
  friend_id TEXT REFERENCES friends(id) ON DELETE SET NULL,
  email TEXT,
  phone TEXT,
  first_name TEXT,
  last_name TEXT,
  orders_count INTEGER DEFAULT 0,
  total_spent REAL DEFAULT 0,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 014_shopify.sql
CREATE TABLE IF NOT EXISTS shopify_tokens (
  id TEXT PRIMARY KEY DEFAULT 'default',
  access_token TEXT NOT NULL,
  scope TEXT,
  expires_at TEXT NOT NULL,
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS abandoned_carts (
  id                        TEXT PRIMARY KEY,
  shopify_checkout_id       TEXT NOT NULL UNIQUE,
  friend_id                 TEXT REFERENCES friends(id) ON DELETE SET NULL,
  shopify_customer_id       TEXT,
  cart_token                TEXT,
  email                     TEXT,
  line_items                TEXT DEFAULT '[]',
  total_price               REAL DEFAULT 0,
  currency                  TEXT DEFAULT 'JPY',
  checkout_url              TEXT,
  status                    TEXT NOT NULL DEFAULT 'pending',
  notification_scheduled_at TEXT,
  notified_at               TEXT,
  recovered_at              TEXT,
  recovered_order_id        TEXT,
  metadata                  TEXT DEFAULT '{}',
  created_at                TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at                TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS restock_requests (
  id                   TEXT PRIMARY KEY,
  friend_id            TEXT REFERENCES friends(id) ON DELETE SET NULL,
  shopify_product_id   TEXT NOT NULL,
  shopify_variant_id   TEXT NOT NULL,
  product_title        TEXT,
  variant_title        TEXT,
  status               TEXT NOT NULL DEFAULT 'waiting',
  notified_at          TEXT,
  cancelled_at         TEXT,
  metadata             TEXT DEFAULT '{}',
  created_at           TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at           TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS shopify_fulfillments (
  id                      TEXT PRIMARY KEY,
  shopify_order_id        TEXT NOT NULL,
  shopify_fulfillment_id  TEXT NOT NULL UNIQUE,
  order_id                TEXT REFERENCES shopify_orders(id) ON DELETE SET NULL,
  friend_id               TEXT REFERENCES friends(id) ON DELETE SET NULL,
  tracking_number         TEXT,
  tracking_url            TEXT,
  tracking_company        TEXT,
  status                  TEXT NOT NULL DEFAULT 'pending',
  line_items              TEXT DEFAULT '[]',
  notified_at             TEXT,
  metadata                TEXT DEFAULT '{}',
  created_at              TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at              TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS shopify_payment_notifications (
  id                TEXT PRIMARY KEY,
  shopify_order_id  TEXT NOT NULL,
  order_id          TEXT REFERENCES shopify_orders(id) ON DELETE SET NULL,
  friend_id         TEXT REFERENCES friends(id) ON DELETE SET NULL,
  financial_status  TEXT NOT NULL,
  total_price       REAL,
  currency          TEXT DEFAULT 'JPY',
  notified_at       TEXT,
  metadata          TEXT DEFAULT '{}',
  created_at        TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS shopify_coupons (
  id                    TEXT PRIMARY KEY,
  code                  TEXT NOT NULL UNIQUE,
  shopify_price_rule_id TEXT,
  shopify_discount_id   TEXT,
  title                 TEXT,
  description           TEXT,
  discount_type         TEXT NOT NULL DEFAULT 'percentage',
  discount_value        REAL NOT NULL DEFAULT 0,
  minimum_order_amount  REAL,
  usage_limit           INTEGER,
  usage_count           INTEGER DEFAULT 0,
  starts_at             TEXT,
  expires_at            TEXT,
  status                TEXT NOT NULL DEFAULT 'active',
  metadata              TEXT DEFAULT '{}',
  created_at            TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at            TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS shopify_coupon_assignments (
  id              TEXT PRIMARY KEY,
  coupon_id       TEXT NOT NULL REFERENCES shopify_coupons(id) ON DELETE CASCADE,
  friend_id       TEXT REFERENCES friends(id) ON DELETE SET NULL,
  assigned_at     TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  used_at         TEXT,
  shopify_order_id TEXT,
  metadata        TEXT DEFAULT '{}',
  created_at      TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS rank_settings (
  id                     TEXT PRIMARY KEY DEFAULT 'default',
  update_interval_days   INTEGER NOT NULL DEFAULT 30,
  calculation_period_months INTEGER NOT NULL DEFAULT 12,
  next_update_at         TEXT,
  metadata               TEXT DEFAULT '{}',
  created_at             TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at             TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS member_ranks (
  id               TEXT PRIMARY KEY,
  name             TEXT NOT NULL UNIQUE,
  min_total_spent  REAL NOT NULL DEFAULT 0,
  min_orders_count INTEGER NOT NULL DEFAULT 0,
  color            TEXT,
  icon             TEXT,
  benefits_json    TEXT DEFAULT '[]',
  sort_order       INTEGER NOT NULL DEFAULT 0,
  is_active        INTEGER NOT NULL DEFAULT 1,
  metadata         TEXT DEFAULT '{}',
  created_at       TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at       TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS rank_coupon_rewards (
  id          TEXT PRIMARY KEY,
  rank_id     TEXT NOT NULL REFERENCES member_ranks(id) ON DELETE CASCADE,
  coupon_id   TEXT NOT NULL REFERENCES shopify_coupons(id) ON DELETE CASCADE,
  reward_type TEXT NOT NULL DEFAULT 'periodic',
  metadata    TEXT DEFAULT '{}',
  created_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 015_shopify_phase2a.sql
CREATE TABLE IF NOT EXISTS friend_ranks (
  id            TEXT PRIMARY KEY,
  friend_id     TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  rank_id       TEXT NOT NULL REFERENCES member_ranks(id) ON DELETE CASCADE,
  total_spent   REAL NOT NULL DEFAULT 0,
  orders_count  INTEGER NOT NULL DEFAULT 0,
  previous_rank_id TEXT,
  calculated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  created_at    TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at    TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 016_ab_tests.sql
CREATE TABLE IF NOT EXISTS ab_tests (
  id                        TEXT PRIMARY KEY,
  title                     TEXT NOT NULL,
  -- バリアントA
  variant_a_message_type    TEXT NOT NULL CHECK (variant_a_message_type IN ('text', 'image', 'flex')),
  variant_a_message_content TEXT NOT NULL,
  variant_a_alt_text        TEXT,
  -- バリアントB
  variant_b_message_type    TEXT NOT NULL CHECK (variant_b_message_type IN ('text', 'image', 'flex')),
  variant_b_message_content TEXT NOT NULL,
  variant_b_alt_text        TEXT,
  -- ターゲティング（broadcastsと同一パターン）
  target_type               TEXT NOT NULL CHECK (target_type IN ('all', 'tag')) DEFAULT 'all',
  target_tag_id             TEXT REFERENCES tags (id) ON DELETE SET NULL,
  -- 分割比率: バリアントAに割り当てる割合（1-99）。残りがB
  split_ratio               INTEGER NOT NULL DEFAULT 50 CHECK (split_ratio BETWEEN 1 AND 99),
  -- ステータス: draft → scheduled → sending → test_sent → winner_sent
  status                    TEXT NOT NULL CHECK (status IN ('draft', 'scheduled', 'sending', 'test_sent', 'winner_sent')) DEFAULT 'draft',
  scheduled_at              TEXT,
  sent_at                   TEXT,
  -- バリアント別カウント
  variant_a_total           INTEGER NOT NULL DEFAULT 0,
  variant_a_success         INTEGER NOT NULL DEFAULT 0,
  variant_b_total           INTEGER NOT NULL DEFAULT 0,
  variant_b_success         INTEGER NOT NULL DEFAULT 0,
  -- 勝者（未決定: NULL, 決定後: 'A' or 'B'）
  winner                    TEXT CHECK (winner IN ('A', 'B')),
  winner_total              INTEGER NOT NULL DEFAULT 0,
  winner_success            INTEGER NOT NULL DEFAULT 0,
  -- トラッキングリンクID（JSON配列）
  variant_a_tracked_link_ids TEXT,
  variant_b_tracked_link_ids TEXT,
  -- マルチアカウント
  line_account_id           TEXT REFERENCES line_accounts (id) ON DELETE SET NULL,
  created_at                TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 016_ab_tests.sql
CREATE TABLE IF NOT EXISTS ab_test_assignments (
  id            TEXT PRIMARY KEY,
  ab_test_id    TEXT NOT NULL REFERENCES ab_tests (id) ON DELETE CASCADE,
  friend_id     TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  variant       TEXT NOT NULL CHECK (variant IN ('A', 'B')),
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 017_shopify_products.sql
CREATE TABLE IF NOT EXISTS shopify_products (
  id                  TEXT PRIMARY KEY,
  shopify_product_id  TEXT NOT NULL UNIQUE,
  title               TEXT NOT NULL,
  description         TEXT,
  vendor              TEXT,
  product_type        TEXT,
  handle              TEXT,
  status              TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'draft', 'archived')),
  image_url           TEXT,
  price               TEXT,
  compare_at_price    TEXT,
  tags                TEXT,
  variants_json       TEXT,
  store_url           TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 017_shopify_products.sql
CREATE TABLE IF NOT EXISTS product_recommendations (
  id                  TEXT PRIMARY KEY,
  friend_id           TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  shopify_product_id  TEXT NOT NULL,
  trigger_type        TEXT NOT NULL CHECK (trigger_type IN ('purchase', 'browse', 'restock', 'manual', 'scheduled')),
  sent_at             TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 018_analytics.sql
CREATE TABLE IF NOT EXISTS analytics_settings (
  id TEXT PRIMARY KEY,
  line_account_id TEXT,
  provider TEXT NOT NULL DEFAULT 'ga4',
  measurement_id TEXT,           -- G-XXXXXXXXXX
  api_secret TEXT,               -- Measurement Protocol API secret
  enabled INTEGER NOT NULL DEFAULT 1,
  config TEXT NOT NULL DEFAULT '{}',  -- JSON: 追加設定
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (line_account_id) REFERENCES line_accounts(id)
);

-- from 018_analytics.sql
CREATE TABLE IF NOT EXISTS analytics_events (
  id TEXT PRIMARY KEY,
  friend_id TEXT,
  event_name TEXT NOT NULL,       -- friend_add, message_open, link_click, purchase
  event_params TEXT DEFAULT '{}', -- JSON: GA4 event parameters
  measurement_id TEXT,
  status TEXT NOT NULL DEFAULT 'sent',  -- sent, failed
  error_message TEXT,
  created_at TEXT NOT NULL,
  FOREIGN KEY (friend_id) REFERENCES friends(id)
);

-- from 018_analytics.sql
CREATE TABLE IF NOT EXISTS utm_templates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  utm_source TEXT NOT NULL DEFAULT 'line',
  utm_medium TEXT NOT NULL DEFAULT 'message',
  utm_campaign TEXT,
  utm_content TEXT,
  utm_term TEXT,
  line_account_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (line_account_id) REFERENCES line_accounts(id)
);

-- from 019_liff_portal.sql
CREATE TABLE IF NOT EXISTS intake_logs (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  friend_id TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  product_name TEXT,
  shopify_product_id TEXT,
  streak_count INTEGER NOT NULL DEFAULT 1,
  note TEXT,
  logged_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 019_liff_portal.sql
CREATE TABLE IF NOT EXISTS intake_reminders (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  friend_id TEXT NOT NULL UNIQUE REFERENCES friends(id) ON DELETE CASCADE,
  reminder_time TEXT NOT NULL DEFAULT '08:00',
  timezone TEXT NOT NULL DEFAULT 'Asia/Tokyo',
  reminder_type TEXT NOT NULL DEFAULT 'morning_push' CHECK(reminder_type IN ('morning_push', 'streak_only')),
  is_active INTEGER NOT NULL DEFAULT 1,
  last_sent_at TEXT,
  snooze_until TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 019_liff_portal.sql
CREATE TABLE IF NOT EXISTS referral_links (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  friend_id TEXT NOT NULL UNIQUE REFERENCES friends(id) ON DELETE CASCADE,
  ref_code TEXT NOT NULL UNIQUE,
  referrer_coupon_id TEXT REFERENCES shopify_coupons(id) ON DELETE SET NULL,
  referred_coupon_id TEXT REFERENCES shopify_coupons(id) ON DELETE SET NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 019_liff_portal.sql
CREATE TABLE IF NOT EXISTS referral_rewards (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  referrer_friend_id TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  referred_friend_id TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  referrer_coupon_id TEXT REFERENCES shopify_coupons(id) ON DELETE SET NULL,
  referred_coupon_id TEXT REFERENCES shopify_coupons(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'rewarded', 'expired')),
  rewarded_at TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 019_liff_portal.sql
CREATE TABLE IF NOT EXISTS recommendation_results (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  friend_id TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  quiz_answers TEXT NOT NULL DEFAULT '{}',
  recommended_product TEXT NOT NULL,
  recommended_product_id TEXT,
  score_breakdown TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 019_liff_portal.sql
CREATE TABLE IF NOT EXISTS health_logs (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  friend_id TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  log_date TEXT NOT NULL,
  weight REAL,
  condition TEXT CHECK(condition IN ('good', 'normal', 'bad')),
  skin_condition TEXT CHECK(skin_condition IN ('good', 'normal', 'bad')),
  meals TEXT DEFAULT '{}',
  sleep_hours REAL,
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 019_liff_portal.sql
CREATE TABLE IF NOT EXISTS ambassadors (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  friend_id TEXT NOT NULL UNIQUE REFERENCES friends(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'invited' CHECK(status IN ('active', 'inactive', 'invited')),
  tier TEXT NOT NULL DEFAULT 'standard' CHECK(tier IN ('standard', 'premium')),
  enrolled_at TEXT,
  total_surveys_completed INTEGER NOT NULL DEFAULT 0,
  total_product_tests INTEGER NOT NULL DEFAULT 0,
  feedback_score REAL,
  preferences TEXT NOT NULL DEFAULT '{"survey_ok":true,"product_test_ok":true,"sns_share_ok":false}',
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 019_liff_portal.sql
CREATE TABLE IF NOT EXISTS daily_tips (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  tip_date TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL DEFAULT 'nutrition' CHECK(category IN ('nutrition', 'sleep', 'exercise', 'skincare', 'mental')),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  image_url TEXT,
  source TEXT NOT NULL DEFAULT 'manual' CHECK(source IN ('manual', 'ai_generated')),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 020_friend_profile_and_dashboard.sql
CREATE TABLE IF NOT EXISTS daily_stats (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  stat_date TEXT NOT NULL,            -- 'YYYY-MM-DD'
  new_friends INTEGER DEFAULT 0,      -- 新規友だち数
  unfollowed INTEGER DEFAULT 0,       -- ブロック/解除数
  total_friends INTEGER DEFAULT 0,    -- 累計友だち数
  orders_count INTEGER DEFAULT 0,     -- 注文件数
  orders_revenue REAL DEFAULT 0,      -- 売上合計
  intake_logs_count INTEGER DEFAULT 0, -- 服用記録数
  referrals_count INTEGER DEFAULT 0,  -- 紹介成立数
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(stat_date)
);

-- from 020_friend_profile_and_dashboard.sql
CREATE TABLE IF NOT EXISTS referral_coupons (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  code TEXT NOT NULL UNIQUE,
  discount_type TEXT NOT NULL DEFAULT 'fixed',  -- 'fixed' | 'percent'
  discount_value REAL NOT NULL DEFAULT 500,
  minimum_order_amount REAL DEFAULT 0,
  expires_days INTEGER NOT NULL DEFAULT 30,     -- 発行日から何日有効
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- from 021_multi_reminders_and_templates.sql
CREATE TABLE IF NOT EXISTS intake_reminders_new (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  friend_id TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  label TEXT NOT NULL DEFAULT '朝食前',
  reminder_time TEXT NOT NULL DEFAULT '08:00',
  timezone TEXT NOT NULL DEFAULT 'Asia/Tokyo',
  reminder_type TEXT NOT NULL DEFAULT 'morning_push' CHECK(reminder_type IN ('morning_push', 'streak_only')),
  is_active INTEGER NOT NULL DEFAULT 1,
  last_sent_at TEXT,
  snooze_until TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 021_multi_reminders_and_templates.sql
CREATE TABLE IF NOT EXISTS reminder_messages (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  time_slot TEXT NOT NULL DEFAULT 'any' CHECK(time_slot IN ('morning', 'noon', 'evening', 'any')),
  message TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'general',
  weight INTEGER NOT NULL DEFAULT 1,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 021_multi_reminders_and_templates.sql
CREATE TABLE IF NOT EXISTS reminder_message_log (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6)))),
  friend_id TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  reminder_message_id TEXT NOT NULL REFERENCES reminder_messages(id) ON DELETE CASCADE,
  sent_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f+09:00', 'now', '+9 hours'))
);

-- from 024_ambassador_feedback.sql
CREATE TABLE IF NOT EXISTS ambassador_feedback (
  id TEXT PRIMARY KEY,
  ambassador_id TEXT NOT NULL REFERENCES ambassadors(id),
  friend_id TEXT NOT NULL REFERENCES friends(id),
  type TEXT NOT NULL DEFAULT 'feedback' CHECK (type IN ('feedback', 'survey', 'product_review')),
  category TEXT DEFAULT 'general' CHECK (category IN ('general', 'product', 'service', 'suggestion', 'other')),
  content TEXT NOT NULL,
  rating INTEGER CHECK (rating BETWEEN 1 AND 5),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S+09:00', 'now', '+9 hours'))
);

-- from 025_ambassador_surveys.sql
CREATE TABLE IF NOT EXISTS ambassador_surveys (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  survey_type TEXT NOT NULL DEFAULT 'survey' CHECK (survey_type IN ('survey', 'product_test', 'nps')),
  questions TEXT NOT NULL DEFAULT '[]',
  -- questions JSON: [{ "id": "q1", "type": "rating|text|choice|multi_choice", "label": "...", "options": ["A","B","C"], "required": true }]
  target_tier TEXT DEFAULT 'all' CHECK (target_tier IN ('all', 'standard', 'premium')),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'closed', 'archived')),
  sent_count INTEGER NOT NULL DEFAULT 0,
  response_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S+09:00', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S+09:00', 'now', '+9 hours'))
);

-- from 025_ambassador_surveys.sql
CREATE TABLE IF NOT EXISTS ambassador_survey_responses (
  id TEXT PRIMARY KEY,
  survey_id TEXT NOT NULL REFERENCES ambassador_surveys(id) ON DELETE CASCADE,
  ambassador_id TEXT NOT NULL REFERENCES ambassadors(id),
  friend_id TEXT NOT NULL REFERENCES friends(id),
  answers TEXT NOT NULL DEFAULT '{}',
  -- answers JSON: { "q1": 4, "q2": "テキスト回答", "q3": ["A","C"] }
  submitted_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S+09:00', 'now', '+9 hours'))
);

-- from 025_ambassador_surveys.sql
CREATE TABLE IF NOT EXISTS ambassador_survey_deliveries (
  id TEXT PRIMARY KEY,
  survey_id TEXT NOT NULL REFERENCES ambassador_surveys(id) ON DELETE CASCADE,
  ambassador_id TEXT NOT NULL REFERENCES ambassadors(id),
  friend_id TEXT NOT NULL REFERENCES friends(id),
  delivered_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S+09:00', 'now', '+9 hours')),
  responded INTEGER NOT NULL DEFAULT 0
);

-- from 026_i18n.sql
CREATE TABLE IF NOT EXISTS translations (
  id TEXT PRIMARY KEY,
  source_text TEXT NOT NULL,
  source_lang TEXT NOT NULL DEFAULT 'ja',
  target_lang TEXT NOT NULL CHECK (target_lang IN ('ja', 'en', 'ko', 'zh', 'th')),
  translated_text TEXT NOT NULL,
  context TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S+09:00', 'now', '+9 hours'))
);

-- from 026_i18n.sql
CREATE TABLE IF NOT EXISTS daily_tips_i18n (
  id TEXT PRIMARY KEY,
  tip_id TEXT NOT NULL,
  lang TEXT NOT NULL CHECK (lang IN ('en', 'ko', 'zh', 'th')),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S+09:00', 'now', '+9 hours'))
);

-- from 027_shopify_oauth.sql
CREATE TABLE IF NOT EXISTS shopify_oauth_states (
  id TEXT PRIMARY KEY,
  nonce TEXT NOT NULL UNIQUE,
  store_domain TEXT NOT NULL,
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  expires_at TEXT NOT NULL
);

-- from 028_shopify_draft_orders.sql
CREATE TABLE IF NOT EXISTS shopify_draft_orders (
  id TEXT PRIMARY KEY,
  friend_id TEXT REFERENCES friends(id),
  shopify_draft_order_id TEXT NOT NULL,
  shopify_draft_order_gid TEXT,
  invoice_url TEXT,
  status TEXT DEFAULT 'open',
  total_price REAL,
  currency TEXT DEFAULT 'JPY',
  line_items TEXT,
  source_order_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- from 029_notification_prefs_and_subscriptions.sql
CREATE TABLE IF NOT EXISTS friend_notification_preferences (
  id TEXT PRIMARY KEY,
  friend_id TEXT NOT NULL REFERENCES friends(id),
  restock_alert INTEGER DEFAULT 1,       -- 在庫復活通知
  delivery_complete INTEGER DEFAULT 1,   -- 配送完了通知
  order_confirm INTEGER DEFAULT 1,       -- 注文確認通知
  campaign_message INTEGER DEFAULT 1,    -- キャンペーン通知
  reorder_reminder INTEGER DEFAULT 1,    -- 再購入リマインダー
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- from 029_notification_prefs_and_subscriptions.sql
CREATE TABLE IF NOT EXISTS subscription_reminders (
  id TEXT PRIMARY KEY,
  friend_id TEXT NOT NULL REFERENCES friends(id),
  product_title TEXT NOT NULL,
  variant_id TEXT,
  interval_days INTEGER NOT NULL DEFAULT 30,  -- リマインド間隔（日）
  next_reminder_at TEXT NOT NULL,
  last_sent_at TEXT,
  is_active INTEGER DEFAULT 1,
  source_order_id TEXT,                       -- 元の注文ID
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- from 029_notification_prefs_and_subscriptions.sql
CREATE TABLE IF NOT EXISTS faq_items (
  id TEXT PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  sort_order INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- from 030_shopify_webhook_log.sql
CREATE TABLE IF NOT EXISTS shopify_webhook_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic TEXT NOT NULL,
  shopify_id TEXT,
  status TEXT NOT NULL DEFAULT 'received',
  summary TEXT,
  error TEXT,
  received_at TEXT NOT NULL
);

-- from 031_feature_gap.sql
CREATE TABLE IF NOT EXISTS groups (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT DEFAULT '',
  color       TEXT DEFAULT '#6B7280',
  created_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 031_feature_gap.sql
CREATE TABLE IF NOT EXISTS friend_groups (
  friend_id  TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  group_id   TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  assigned_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  PRIMARY KEY (friend_id, group_id)
);

-- from 031_feature_gap.sql
CREATE TABLE IF NOT EXISTS tag_elapsed_deliveries (
  id               TEXT PRIMARY KEY,
  name             TEXT NOT NULL,
  trigger_tag_id   TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  elapsed_days     INTEGER NOT NULL,
  message_type     TEXT NOT NULL DEFAULT 'text',
  message_content  TEXT NOT NULL,
  is_active        INTEGER NOT NULL DEFAULT 1,
  send_hour        INTEGER NOT NULL DEFAULT 10,
  created_at       TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at       TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 031_feature_gap.sql
CREATE TABLE IF NOT EXISTS tag_elapsed_delivery_logs (
  id           TEXT PRIMARY KEY,
  delivery_id  TEXT NOT NULL REFERENCES tag_elapsed_deliveries(id) ON DELETE CASCADE,
  friend_id    TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  sent_at      TEXT NOT NULL,
  UNIQUE(delivery_id, friend_id)
);

-- from 032_feature_gap_v2.sql
CREATE TABLE IF NOT EXISTS liff_carts (
  id                TEXT PRIMARY KEY,
  friend_id         TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  shopify_variant_id TEXT NOT NULL,
  shopify_product_id TEXT,
  title             TEXT,
  image_url         TEXT,
  price             REAL NOT NULL DEFAULT 0,
  quantity          INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at        TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 035_badges.sql
CREATE TABLE IF NOT EXISTS badges (
  code        TEXT PRIMARY KEY,                  -- intake_streak_7 等
  category    TEXT NOT NULL,                     -- intake / purchase / referral / seasonal
  name        TEXT NOT NULL,                     -- 7日連続
  description TEXT,                              -- バッジの説明文
  icon        TEXT,                              -- 絵文字 or icon URL
  threshold   INTEGER,                           -- 獲得閾値 (streak日数 / 購入回数 等)
  rarity      TEXT NOT NULL DEFAULT 'common',    -- common / rare / epic / legendary
  is_active   INTEGER NOT NULL DEFAULT 1,        -- 0 = 廃止
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 035_badges.sql
CREATE TABLE IF NOT EXISTS friend_badges (
  id         TEXT PRIMARY KEY,
  friend_id  TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  badge_code TEXT NOT NULL REFERENCES badges(code) ON DELETE CASCADE,
  earned_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (friend_id, badge_code)                 -- 同一バッジの重複獲得防止
);

-- from 036_food_logs.sql
CREATE TABLE IF NOT EXISTS food_logs (
  id              TEXT PRIMARY KEY,
  friend_id       TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  ate_at          TEXT NOT NULL,                    -- ISO8601 JST (撮影時刻 or 手動入力時刻)
  meal_type       TEXT,                             -- breakfast / lunch / dinner / snack / NULL
  image_url       TEXT,                             -- R2 公開 URL (NULL なら手動テキスト入力のみ)
  raw_text        TEXT,                             -- ユーザ入力 / キャプション (検索用)
  ai_analysis     TEXT,                             -- JSON: {calories, protein_g, fat_g, carbs_g, fiber_g, items[{name,qty}], notes, model_version}
  total_calories  INTEGER,                          -- ai_analysis.calories の冗長キャッシュ
  total_protein_g REAL,
  total_fat_g     REAL,
  total_carbs_g   REAL,
  analysis_status TEXT NOT NULL DEFAULT 'pending',  -- pending / completed / failed
  error_message   TEXT,                             -- 解析失敗時のエラー要約 (ユーザ表示用)
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- from 036_food_logs.sql
CREATE TABLE IF NOT EXISTS daily_food_stats (
  friend_id        TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  date             TEXT NOT NULL,                   -- YYYY-MM-DD (JST)
  total_calories   INTEGER NOT NULL DEFAULT 0,
  total_protein_g  REAL NOT NULL DEFAULT 0,
  total_fat_g      REAL NOT NULL DEFAULT 0,
  total_carbs_g    REAL NOT NULL DEFAULT 0,
  meal_count       INTEGER NOT NULL DEFAULT 0,
  last_updated     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  PRIMARY KEY (friend_id, date)
);

-- from 036_food_logs.sql
CREATE TABLE IF NOT EXISTS monthly_food_reports (
  friend_id    TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  year_month   TEXT NOT NULL,                    -- "2026-04" (JST)
  summary_text TEXT NOT NULL,                    -- AI 生成テキスト (薬機ガード後)
  meal_count   INTEGER NOT NULL DEFAULT 0,       -- 集計対象になった食事ログ数
  avg_calories INTEGER,                          -- 月平均カロリー (NULL=データ不足)
  generated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  PRIMARY KEY (friend_id, year_month)
);

-- from 037_nutrition_coach.sql
CREATE TABLE IF NOT EXISTS nutrition_recommendations (
  id                     TEXT PRIMARY KEY,
  friend_id              TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  generated_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  -- 栄養不足の解析結果 (JSON 配列):
  --   [{ key:'protein_low', observedAvg:55, targetAvg:80, severity:'mild' }, ...]
  deficit_json           TEXT NOT NULL,
  -- 提案 SKU 群 (JSON 配列):
  --   [{ shopifyProductId:'gid://shopify/Product/...', productTitle:'...',
  --      copy:'...', deficitKey:'protein_low' }, ...]
  sku_suggestions_json   TEXT NOT NULL,
  -- AI 生成のパーソナルメッセージ (薬機ガード後)。失敗時はテンプレ
  ai_message             TEXT NOT NULL,
  -- ステート: active (生成直後) / dismissed (友だちが却下) / clicked / converted
  status                 TEXT NOT NULL DEFAULT 'active',
  -- 配信タイミング (push 送信時刻)。LIFF 単体表示時は NULL
  sent_at                TEXT,
  clicked_at             TEXT,
  converted_at           TEXT,
  -- CV 連動: クリック → 購入したら conversion_events.id を紐付け
  conversion_event_id    TEXT REFERENCES conversion_events(id) ON DELETE SET NULL
);

-- from 037_nutrition_coach.sql
CREATE TABLE IF NOT EXISTS nutrition_sku_map (
  deficit_key         TEXT PRIMARY KEY,
  shopify_product_id  TEXT NOT NULL,
  product_title       TEXT NOT NULL,
  copy_template       TEXT NOT NULL,
  is_active           INTEGER NOT NULL DEFAULT 1,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- Indexes from migrations
CREATE INDEX IF NOT EXISTS idx_entry_routes_ref ON entry_routes (ref_code);
CREATE INDEX IF NOT EXISTS idx_ref_tracking_ref    ON ref_tracking (ref_code);
CREATE INDEX IF NOT EXISTS idx_ref_tracking_friend ON ref_tracking (friend_id);
CREATE INDEX IF NOT EXISTS idx_link_clicks_link ON link_clicks (tracked_link_id);
CREATE INDEX IF NOT EXISTS idx_link_clicks_friend ON link_clicks (friend_id);
CREATE INDEX IF NOT EXISTS idx_form_submissions_form ON form_submissions (form_id);
CREATE INDEX IF NOT EXISTS idx_form_submissions_friend ON form_submissions (friend_id);
CREATE INDEX IF NOT EXISTS idx_line_accounts_bot_user_id ON line_accounts(bot_user_id);
CREATE INDEX IF NOT EXISTS idx_shopify_orders_friend ON shopify_orders(friend_id);
CREATE INDEX IF NOT EXISTS idx_shopify_orders_email ON shopify_orders(email);
CREATE INDEX IF NOT EXISTS idx_shopify_orders_shopify_customer ON shopify_orders(shopify_customer_id);
CREATE INDEX IF NOT EXISTS idx_shopify_customers_friend ON shopify_customers(friend_id);
CREATE INDEX IF NOT EXISTS idx_shopify_customers_email ON shopify_customers(email);
CREATE INDEX IF NOT EXISTS idx_shopify_customers_phone ON shopify_customers(phone);
CREATE INDEX IF NOT EXISTS idx_abandoned_carts_friend ON abandoned_carts(friend_id);
CREATE INDEX IF NOT EXISTS idx_abandoned_carts_status ON abandoned_carts(status);
CREATE INDEX IF NOT EXISTS idx_abandoned_carts_scheduled ON abandoned_carts(status, notification_scheduled_at);
CREATE INDEX IF NOT EXISTS idx_abandoned_carts_cart_token ON abandoned_carts(cart_token);
CREATE INDEX IF NOT EXISTS idx_abandoned_carts_email ON abandoned_carts(email);
CREATE INDEX IF NOT EXISTS idx_restock_requests_friend ON restock_requests(friend_id);
CREATE INDEX IF NOT EXISTS idx_restock_requests_variant ON restock_requests(shopify_variant_id, status);
CREATE INDEX IF NOT EXISTS idx_restock_requests_product ON restock_requests(shopify_product_id, status);
CREATE INDEX IF NOT EXISTS idx_restock_requests_status ON restock_requests(status);
CREATE INDEX IF NOT EXISTS idx_shopify_fulfillments_order ON shopify_fulfillments(shopify_order_id);
CREATE INDEX IF NOT EXISTS idx_shopify_fulfillments_friend ON shopify_fulfillments(friend_id);
CREATE INDEX IF NOT EXISTS idx_shopify_fulfillments_status ON shopify_fulfillments(status);
CREATE INDEX IF NOT EXISTS idx_payment_notifications_order ON shopify_payment_notifications(shopify_order_id);
CREATE INDEX IF NOT EXISTS idx_payment_notifications_friend ON shopify_payment_notifications(friend_id);
CREATE INDEX IF NOT EXISTS idx_shopify_coupons_code ON shopify_coupons(code);
CREATE INDEX IF NOT EXISTS idx_shopify_coupons_status ON shopify_coupons(status);
CREATE INDEX IF NOT EXISTS idx_coupon_assignments_coupon ON shopify_coupon_assignments(coupon_id);
CREATE INDEX IF NOT EXISTS idx_coupon_assignments_friend ON shopify_coupon_assignments(friend_id);
CREATE INDEX IF NOT EXISTS idx_member_ranks_sort ON member_ranks(sort_order);
CREATE INDEX IF NOT EXISTS idx_rank_coupon_rewards_rank ON rank_coupon_rewards(rank_id);
CREATE INDEX IF NOT EXISTS idx_rank_coupon_rewards_type ON rank_coupon_rewards(rank_id, reward_type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_friend_ranks_friend ON friend_ranks(friend_id);
CREATE INDEX IF NOT EXISTS idx_friend_ranks_rank ON friend_ranks(rank_id);
CREATE INDEX IF NOT EXISTS idx_ab_tests_status ON ab_tests (status);
CREATE INDEX IF NOT EXISTS idx_ab_tests_line_account ON ab_tests (line_account_id);
CREATE INDEX IF NOT EXISTS idx_ab_assign_test ON ab_test_assignments (ab_test_id);
CREATE INDEX IF NOT EXISTS idx_ab_assign_friend ON ab_test_assignments (friend_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ab_assign_unique ON ab_test_assignments (ab_test_id, friend_id);
CREATE INDEX IF NOT EXISTS idx_shopify_products_status ON shopify_products (status);
CREATE INDEX IF NOT EXISTS idx_shopify_products_type ON shopify_products (product_type);
CREATE INDEX IF NOT EXISTS idx_prod_rec_friend ON product_recommendations (friend_id);
CREATE INDEX IF NOT EXISTS idx_prod_rec_product ON product_recommendations (shopify_product_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_prod_rec_unique ON product_recommendations (friend_id, shopify_product_id, trigger_type);
CREATE INDEX IF NOT EXISTS idx_analytics_events_friend ON analytics_events(friend_id);
CREATE INDEX IF NOT EXISTS idx_analytics_events_name ON analytics_events(event_name);
CREATE INDEX IF NOT EXISTS idx_analytics_events_created ON analytics_events(created_at);
CREATE INDEX IF NOT EXISTS idx_utm_templates_account ON utm_templates(line_account_id);
CREATE INDEX IF NOT EXISTS idx_intake_logs_friend ON intake_logs(friend_id);
CREATE INDEX IF NOT EXISTS idx_intake_logs_logged ON intake_logs(friend_id, logged_at);
CREATE INDEX IF NOT EXISTS idx_intake_reminders_active ON intake_reminders(is_active, reminder_time);
CREATE INDEX IF NOT EXISTS idx_referral_links_ref ON referral_links(ref_code);
CREATE INDEX IF NOT EXISTS idx_referral_rewards_referrer ON referral_rewards(referrer_friend_id);
CREATE INDEX IF NOT EXISTS idx_referral_rewards_referred ON referral_rewards(referred_friend_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_friend ON recommendation_results(friend_id);
CREATE INDEX IF NOT EXISTS idx_health_logs_friend ON health_logs(friend_id);
CREATE INDEX IF NOT EXISTS idx_health_logs_date ON health_logs(friend_id, log_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_health_logs_unique ON health_logs(friend_id, log_date);
CREATE INDEX IF NOT EXISTS idx_ambassadors_status ON ambassadors(status);
CREATE INDEX IF NOT EXISTS idx_ambassadors_friend ON ambassadors(friend_id);
CREATE INDEX IF NOT EXISTS idx_daily_tips_date ON daily_tips(tip_date);
CREATE INDEX IF NOT EXISTS idx_intake_reminders_active_time ON intake_reminders(is_active, reminder_time);
CREATE INDEX IF NOT EXISTS idx_intake_reminders_friend ON intake_reminders(friend_id);
CREATE INDEX IF NOT EXISTS idx_intake_reminders_friend_count ON intake_reminders(friend_id, is_active);
CREATE INDEX IF NOT EXISTS idx_reminder_messages_slot ON reminder_messages(time_slot, is_active);
CREATE INDEX IF NOT EXISTS idx_reminder_msg_log_friend ON reminder_message_log(friend_id, sent_at);
CREATE INDEX IF NOT EXISTS idx_reminder_msg_log_msg ON reminder_message_log(reminder_message_id);
CREATE INDEX IF NOT EXISTS idx_ambassador_feedback_ambassador ON ambassador_feedback(ambassador_id);
CREATE INDEX IF NOT EXISTS idx_ambassador_feedback_type ON ambassador_feedback(type);
CREATE INDEX IF NOT EXISTS idx_ambassador_surveys_status ON ambassador_surveys(status);
CREATE INDEX IF NOT EXISTS idx_ambassador_surveys_type ON ambassador_surveys(survey_type);
CREATE INDEX IF NOT EXISTS idx_survey_responses_survey ON ambassador_survey_responses(survey_id);
CREATE INDEX IF NOT EXISTS idx_survey_responses_ambassador ON ambassador_survey_responses(ambassador_id);
CREATE INDEX IF NOT EXISTS idx_survey_deliveries_survey ON ambassador_survey_deliveries(survey_id);
CREATE INDEX IF NOT EXISTS idx_survey_deliveries_ambassador ON ambassador_survey_deliveries(ambassador_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_survey_responses_unique ON ambassador_survey_responses(survey_id, ambassador_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_survey_deliveries_unique ON ambassador_survey_deliveries(survey_id, ambassador_id);
CREATE INDEX IF NOT EXISTS idx_translations_lookup ON translations(source_lang, target_lang, source_text);
CREATE UNIQUE INDEX IF NOT EXISTS idx_translations_unique ON translations(source_text, source_lang, target_lang);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tips_i18n_unique ON daily_tips_i18n(tip_id, lang);
CREATE INDEX IF NOT EXISTS idx_tips_i18n_lang ON daily_tips_i18n(lang);
CREATE INDEX IF NOT EXISTS idx_shopify_draft_orders_friend
  ON shopify_draft_orders(friend_id);
CREATE INDEX IF NOT EXISTS idx_shopify_draft_orders_shopify_id
  ON shopify_draft_orders(shopify_draft_order_id);
CREATE INDEX IF NOT EXISTS idx_notif_prefs_friend ON friend_notification_preferences(friend_id);
CREATE INDEX IF NOT EXISTS idx_sub_reminders_friend ON subscription_reminders(friend_id);
CREATE INDEX IF NOT EXISTS idx_sub_reminders_next ON subscription_reminders(next_reminder_at, is_active);
CREATE INDEX IF NOT EXISTS idx_webhook_log_topic ON shopify_webhook_log(topic);
CREATE INDEX IF NOT EXISTS idx_webhook_log_received ON shopify_webhook_log(received_at);
CREATE INDEX IF NOT EXISTS idx_friends_blacklisted ON friends(is_blacklisted);
CREATE INDEX IF NOT EXISTS idx_friend_groups_group_id ON friend_groups(group_id);
CREATE INDEX IF NOT EXISTS idx_tag_elapsed_tag ON tag_elapsed_deliveries(trigger_tag_id);
CREATE INDEX IF NOT EXISTS idx_tag_elapsed_logs_delivery ON tag_elapsed_delivery_logs(delivery_id);
CREATE INDEX IF NOT EXISTS idx_friends_status ON friends(status);
CREATE INDEX IF NOT EXISTS idx_friends_assigned_staff ON friends(assigned_staff_id);
CREATE INDEX IF NOT EXISTS idx_liff_carts_friend ON liff_carts(friend_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_liff_carts_friend_variant ON liff_carts(friend_id, shopify_variant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_intake_logs_unique_meal
  ON intake_logs (friend_id, substr(logged_at, 1, 10), meal_type)
  WHERE meal_type IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_intake_logs_friend_date
  ON intake_logs (friend_id, logged_at);
CREATE INDEX IF NOT EXISTS idx_badges_category ON badges (category, sort_order);
CREATE INDEX IF NOT EXISTS idx_friend_badges_friend ON friend_badges (friend_id);
CREATE INDEX IF NOT EXISTS idx_friend_badges_earned ON friend_badges (earned_at);
CREATE INDEX IF NOT EXISTS idx_food_logs_friend_ate
  ON food_logs (friend_id, ate_at DESC);
CREATE INDEX IF NOT EXISTS idx_food_logs_friend_date
  ON food_logs (friend_id, substr(ate_at, 1, 10));
CREATE INDEX IF NOT EXISTS idx_daily_food_stats_friend
  ON daily_food_stats (friend_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_food_logs_pending
  ON food_logs (friend_id, created_at)
  WHERE analysis_status = 'pending';
CREATE INDEX IF NOT EXISTS idx_monthly_food_reports_generated
  ON monthly_food_reports (friend_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_nutrition_reco_friend
  ON nutrition_recommendations (friend_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_nutrition_reco_active
  ON nutrition_recommendations (status, generated_at)
  WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_nutrition_reco_status_generated
  ON nutrition_recommendations (status, generated_at DESC);
